doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL_MASTER)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

            GoogleApi:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/GoogleApi'
                prefix: 'Infrastructure\Persistence\Doctrine\GoogleApi'
                alias: GoogleApi

#            SpySerp:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/SpySerp'
#                prefix: 'Infrastructure\Persistence\Doctrine\SpySerp'
#                alias: SpySerp

#            SeRanking:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/SeRanking'
#                prefix: 'Infrastructure\Persistence\Doctrine\SeRanking'
#                alias: SeRanking

        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
