networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker-network

services:
  database:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME}.database.postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  database-slave:
    container_name: ${COMPOSE_PROJECT_NAME}.database.mariadb
    image: mariadb:10.11.15
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      TZ: ${TZ}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./docker/database/mariadb/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./volumes/mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h ${MYSQL_HOST} -u root -p${MYSQL_ROOT_PASSWORD} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default
    restart: unless-stopped

  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}.application
    build:
      context: .
      dockerfile: docker/php/php-fpm.Dockerfile
      args:
        - APP_ENV=${APP_ENV}
        - TZ=${TZ}
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - ./:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php-fpm/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php-fpm/conf.d/xdebug.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm/conf.d/www.conf
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}.nginx
    image: nginx:1.29-alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/application.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hexagonal.rule=Host(`hexagonal.localhost`)"
      - "traefik.http.routers.hexagonal.tls=true"
      - "traefik.http.routers.hexagonal.entrypoints=https"
      - "traefik.http.services.hexagonal.loadbalancer.server.port=80"
    depends_on:
      - php-fpm
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}.rabbitmq
    image: rabbitmq:4.2.1-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.routers.rabbitmq.entrypoints=https"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/mnesia
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - default
    restart: unless-stopped

  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}.traefik
    image: traefik:3.2.0
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./docker/traefik/certs/:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - default
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
